<?php

namespace App\Repositories;

use Blok\Repository\AbstractEloquentRepository;

class UserRepository extends AbstractEloquentRepository
{
    public function model()
    {
        return \App\Models\User::class;
    }

    public function create(array $data)
    {
        $user = parent::create($data); // TODO: Change the autogenerated stub

        /**
         * Here you can override any method and add your business logic here
         */

        return $user;
    }


}
